name: ASP.NET  API CI/Cd

on:
  push:
    branches: ["master"]
  pull_request: 
    branches: ["master"]
jobs:

 build:
  name: Compilação
  runs-on: ubuntu-latest
  steps:
    - name: Checkout do código
      uses: actions/checkout@v3
    - name: Compilar
      run: echo "Compilando a aplicação..."
      
 test: 
    name: Testes 
    runs-on: ubuntu-latest 
    needs: build 
    steps: 
        - name: Checkout do código 
          uses: actions/checkout@v3 
        - name: Executar os testes 
          run: echo "Rodando os testes..."
 deploy:
    name: Implanção
    runs-on: ubuntu-latest
    needs: test
    steps:
     - name: Chekout do código
       uses: action/checkout@v3
     - name: Impatação da aplicação
       run: echo "Impatando o sistema em produção..."
